config/routes.rb
SimpleChat::Application.routes.draw do
  match '/pusher/auth' => 'pusher#auth'

  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' } do
    root :to => 'users/registrations#new'
  end
  
  resources :chat_rooms, :only => [:index, :show, :create] do
    member do
      get 'join'
      post 'send_message'  
      post 'update_nickname'
    end
  end

  match 'chat_rooms' => 'chat_rooms#index', :as => 'user_root'



end

app/models/chat_room.rb
class ChatRoom
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, :type => String
  field :channel_name, :type => String

  embeds_many :messages 
  has_and_belongs_to_many :users, dependent: :nullify
  belongs_to :owner, class_name: 'User', inverse_of: :my_chat_room
  
  before_create :create_channel_name
  validates_presence_of :name

  protected
  def create_channel_name
    self.channel_name = "presence-channel-#{SecureRandom.hex(10)}"
  end
end

app/models/message.rb
class Message
  include Mongoid::Document
  include Mongoid::Timestamps
  field :content, :type => String
  belongs_to :user
  embedded_in :chat_room

  validates_presence_of :content
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :rememberable, :trackable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :validatable
  field :nickname, type: String

  before_create :create_nickname
  has_and_belongs_to_many :chat_rooms, dependent: :nullify

  has_one :my_chat_room, class_name: 'ChatRoom', inverse_of: :owner
  
  protected
  def create_nickname
    self.nickname = email.match(/(.+)@/i)[1].to_s 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @chat_rooms = ChatRoom.all
  end

  def show
    @chat_room = ChatRoom.find(params[:id])
    if @chat_room.nil? 
      redirect_to chat_rooms_path
    end
  end

  def create
    if my_room = current_user.my_chat_room
      redirect_to chat_room_path(my_room), 
                  :notice => "You are already in this room"
    else 
      @chat_room = current_user.build_my_chat_room(name: params[:name])
      if @chat_room.save
        redirect_to chat_room_path(@chat_room), 
                    :notice => "New chat room -#{@chat_room.name}- created!"
      else
        redirect_to chat_rooms_path 
      end
    end
  end
  
  def join
    @chat_room = ChatRoom.find(params[:id])
    if current_user == @chat_room.owner || current_user.chat_rooms.include?(@chat_room)
      redirect_to chat_room_path(@chat_room), notice: "Your are already in this room" 
    else 
      @chat_room.users << current_user
      @chat_room.save! # causes problem here
      redirect_to chat_room_path(@chat_room)
    end
  end
  
  # Ajax calls 

  def send_message
    @chat_room = ChatRoom.find(params[:id])  
    @msg = @chat_room.messages.build({content: params[:content]})
    @msg.user = current_user
    if @msg.save
      payload = @msg.attributes
      payload[:user] = { nickname: current_user.nickname }
      Pusher[@chat_room.channel_name].trigger( 'send_message', payload ) 
      head :ok
    else
      head :bad_request
    end
  end

  def update_nickname
    @chat_room = ChatRoom.find(params[:id])  
    old_nickname = current_user.nickname
    if current_user.update_attributes(nickname: params[:nickname])
      payload = { old_nickname: old_nickname, nickname: params[:nickname], user_id: current_user.id }
      Pusher[@chat_room.channel_name].trigger('update_nickname',  payload)
      head :ok
    else
      head 500 
    end
  end 

end

app/controllers/pusher_controller.rb
class PusherController < ApplicationController
  protect_from_forgery :except => :auth
  def auth
    raise "Unknown channel" unless params[:channel_name] =~ /presence-channel-\w+/
    channel = Pusher["#{params[:channel_name]}"]
    if user_signed_in? 
      response = channel.authenticate(params[:socket_id], {
        :user_id => current_user.id,
        :user_info => { :nickname => current_user.nickname }
      })
      render :json => response
    else
      redirect_to :root, :notice => 'You have to sign in/sign up first'
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  protected
  def sign_out
    # Check if the current_user own a chat room 
    # Maybe other dependency setting would do the trick
    if room = current_user.my_chat_room
      # promote an user to be the owner
      if room.users.any?
        candidate = room.users.first
        room.owner = candidate 
        room.users.delete(candidate)
        room.save
      else
        room.users = nil
        room.delete
      end
    end
    # remove all the existence of the user in other rooms
    if current_user.chat_rooms.any?
      current_user.chat_rooms = nil
    end
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def url2html(msg)
    exp = /(\b(https?|ftp|file):\/\/[-A-Z0-9+&@#\/%?=~_|!:,.;]*[-A-Z0-9+&@#\/%=~_|])/i
    if obj = msg.match(exp)
      url = "<a href='#{obj[1]}' target='_blank'>#{obj[1]}</a>"
      msg.gsub(exp, url) 
    else 
      msg
    end
  end
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/helpers/pusher_helper.rb
module PusherHelper
end

app/helpers/users/sessions_helper.rb
module Users::SessionsHelper
end

app/views/chat_rooms/create.html.erb
<h1>ChatRoom#create</h1>
<p>Find me in app/views/chat_room/create.html.erb</p>

app/views/chat_rooms/index.html.haml
- if @chat_rooms.any?
  %section
    %h3 Avialable rooms
    %ul
      - @chat_rooms.each do |room|
        %li= link_to "#{room.name} | #{room.users.count + 1} people online", join_chat_room_path(room)  
%section
  %h3 Create a new room
  = form_tag '/chat_rooms', :method => :post, :id => 'form-1' do
    .hdiv= text_field_tag 'name', nil, :size => 12, :maxlength => 15, :class => "text" 
    .hdiv= submit_tag 'Create', :class => "button"
  

app/views/chat_rooms/show.html.haml
= content_for :javascript_includes do
  = javascript_include_tag "chat-room"
  = javascript_include_tag "chat-room.functions"
:javascript
  channel = "#{@chat_room.channel_name}"
  chatroom_id = "#{@chat_room.id}"
  my_id = "#{current_user.id}"
  old_nickname = "#{current_user.nickname}"
  
#chat-box
  .left-panel
    #info-bar
      .left #{@chat_room.name} 
      .right
        %span New nickname 
        %span#name-update{ :style => "display:none;" }
          = text_field_tag 'nickname', nil, :size => 10, :maxlength => 15, :id => "input-2"
          = submit_tag 'save', :id => "button-3"
      .clearfix
    #msg-box-1
      %ul
        - @chat_room.messages.each do |msg|
          - if msg.user_id == current_user.id 
            %li{ :id => msg.id, :class => 'self' } <span>#{msg.user.nickname} : </span> #{url2html(msg.content).html_safe}
          - else
            %li{ :id => msg.id } <span>#{msg.user.nickname} :</span> #{url2html(msg.content).html_safe}
      #msg-overlay
    #msg-box-2
      = text_area_tag 'message', nil, :id => 'message', :disabled => 'disabled'
      #button-2 Send 
  .right-panel
    #user-panel
      %span#member_count 0
      %ul
        %li{ :id => @chat_room.owner.id }= @chat_room.owner.nickname
        - @chat_room.users.each do |user|
          %li{ :id => user.id }= user.nickname

app/views/layouts/_content.html.haml
.content
  = yield

app/views/layouts/_footer.html.haml
.footer
  %p Copyright &copy;2012 Webber Q. Han

app/views/layouts/_header.html.haml
%header
  #banner
    .banner-in
      - if user_signed_in?
        %span <i>#{current_user.email}</i>
        = link_to "logout", destroy_user_session_path, :method => :delete
      - else
        = link_to "login", new_user_session_path
  %hgroup
    %h1= link_to "Simple Chat", root_path
    %h2 Created by Webber Q. Han

app/views/layouts/application.html.haml
!!! Basic
%html
  %head
    %title SimpleChat
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = javascript_include_tag "http://js.pusher.com/1.11/pusher.min.js"
    = yield :javascript_includes
    = csrf_meta_tags
    :javascript
      Pusher.log = function(message) {
        if (window.console && window.console.log) window.console.log(message);
      };
      var PUSHER_KEY = "#{Pusher.key}"   
  %body
    .container
      = render :partial => "layouts/header"
      %hr
      = render :partial => "layouts/content" 
      %hr
      = render :partial => "layouts/footer"
    = debug(params) if Rails.env.development?

app/views/pusher/auth.html.erb
<h1>Pusher#auth</h1>
<p>Find me in app/views/pusher/auth.html.erb</p>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_user_session_path %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_user_registration_path %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>